// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQWvybtBirpPaVyX4X0v81eb0m1L-OCZg',
    appId: '1:335932645497:android:3e9f795029fc8dbeff74a8',
    messagingSenderId: '335932645497',
    projectId: 'todo-app-bb289',
    storageBucket: 'todo-app-bb289.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSa11oLiw7-mfrq73UpDljGZU9wnDzfaM',
    appId: '1:335932645497:ios:10720d638f14bafcff74a8',
    messagingSenderId: '335932645497',
    projectId: 'todo-app-bb289',
    storageBucket: 'todo-app-bb289.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5P9A4f4TmmJY7xKTojCFtqw__IkSjPLw',
    appId: '1:335932645497:web:8c1fb8adc8e2d6e6ff74a8',
    messagingSenderId: '335932645497',
    projectId: 'todo-app-bb289',
    authDomain: 'todo-app-bb289.firebaseapp.com',
    storageBucket: 'todo-app-bb289.firebasestorage.app',
  );
}
